export enum RouteNames {
  DASHBOARD = 'Dashboard',
  LANDING_REDIRECT = 'LandingRedirect',
  QUOTE_REQUEST = 'QuoteRequest',
  LANDING = 'Landing',
  ABOUT = 'About',
  USERS = 'Users',
  EMPLOYEES = 'Employees',
  CUSTOMERS = 'Customers',
  JOBS = 'Jobs',
  EMAILS = 'Emails',
  CALLBACK = 'Callback',
  ERROR_PAGE = 'ErrorPage',
  NOT_FOUND = 'NotFound',
}
